const dare = (player0 = 'Spieler 1', player1 = 'Spieler 2') => {
  player0 = `<i>${player0[0]}</i>`
  player1 = `<i>${player1[0]}</i>`
  return {
    normal: [
      [`${player0} normal 01 ${player1}`, 1],
      [`${player0} normal 02 ${player1}`, 2],
      [`${player0} normal 03 ${player1}`, 3],
      [`${player0} normal 04 ${player1}`, 4],
      [`${player0} normal 05 ${player1}`, 5],
      [`${player0} normal 06 ${player1}`, 6],
      [`${player0} normal 07 ${player1}`, 7],
      [`${player0} normal 08 ${player1}`, 8],
      [`${player0} normal 09 ${player1}`, 9],
      [`${player0} normal 10 ${player1}`, 10],
    ],
    partner: [
      [`${player0} partner 01 ${player1}`, 1],
      [`${player0} partner 02 ${player1}`, 2],
      [`${player0} partner 03 ${player1}`, 3],
      [`${player0} partner 04 ${player1}`, 4],
      [`${player0} partner 05 ${player1}`, 5],
      [`${player0} partner 06 ${player1}`, 6],
      [`${player0} partner 07 ${player1}`, 7],
      [`${player0} partner 08 ${player1}`, 8],
      [`${player0} partner 09 ${player1}`, 9],
      [`${player0} partner 10 ${player1}`, 10],
    ],
    crush: [
      [`${player0} crush 01 ${player1}`, 1],
      [`${player0} crush 02 ${player1}`, 2],
      [`${player0} crush 03 ${player1}`, 3],
      [`${player0} crush 04 ${player1}`, 4],
      [`${player0} crush 05 ${player1}`, 5],
      [`${player0} crush 06 ${player1}`, 6],
      [`${player0} crush 07 ${player1}`, 7],
      [`${player0} crush 08 ${player1}`, 8],
      [`${player0} crush 09 ${player1}`, 9],
      [`${player0} crush 10 ${player1}`, 10],
    ],
    differentSex: [
      [`${player0} differentSex 01 ${player1}`, 1],
      [`${player0} differentSex 02 ${player1}`, 2],
      [`${player0} differentSex 03 ${player1}`, 3],
      [`${player0} differentSex 04 ${player1}`, 4],
      [`${player0} differentSex 05 ${player1}`, 5],
      [`${player0} differentSex 06 ${player1}`, 6],
      [`${player0} differentSex 07 ${player1}`, 7],
      [`${player0} differentSex 08 ${player1}`, 8],
      [`${player0} differentSex 09 ${player1}`, 9],
      [`${player0} differentSex 10 ${player1}`, 10],
    ],
    sameSex: [
      [`${player0} sameSex 01 ${player1}`, 1],
      [`${player0} sameSex 02 ${player1}`, 2],
      [`${player0} sameSex 03 ${player1}`, 3],
      [`${player0} sameSex 04 ${player1}`, 4],
      [`${player0} sameSex 05 ${player1}`, 5],
      [`${player0} sameSex 06 ${player1}`, 6],
      [`${player0} sameSex 07 ${player1}`, 7],
      [`${player0} sameSex 08 ${player1}`, 8],
      [`${player0} sameSex 09 ${player1}`, 9],
      [`${player0} sameSex 10 ${player1}`, 10],
    ],
    imaginaryTask: `${player1} denke dir eine Aufgabe für ${player0} aus!`,
    probabilityNormal: 0.3,
    probabilityPartnerCrush: 0.6,
  }
}
