const truth = (player0 = 'Spieler 1', player1 = 'Spieler 2') => {
  player0 = `<i>${player0[0]}</i>`
  player1 = `<i>${player1[0]}</i>`
  return {
    normal: [
      [`${player0} normal01 ${player1}`, 1],
      [`${player0} normal02 ${player1}`, 2],
      [`${player0} normal03 ${player1}`, 3],
      [`${player0} normal04 ${player1}`, 4],
      [`${player0} normal05 ${player1}`, 5],
      [`${player0} normal06 ${player1}`, 6],
      [`${player0} normal07 ${player1}`, 7],
      [`${player0} normal08 ${player1}`, 8],
      [`${player0} normal09 ${player1}`, 9],
      [`${player0} normal10 ${player1}`, 10],
    ],
    partner: [
      [`${player0} partner01 ${player1}`, 1],
      [`${player0} partner02 ${player1}`, 2],
      [`${player0} partner03 ${player1}`, 3],
      [`${player0} partner04 ${player1}`, 4],
      [`${player0} partner05 ${player1}`, 5],
      [`${player0} partner06 ${player1}`, 6],
      [`${player0} partner07 ${player1}`, 7],
      [`${player0} partner08 ${player1}`, 8],
      [`${player0} partner09 ${player1}`, 9],
      [`${player0} partner10 ${player1}`, 10],
    ],
    crush: [
      [`${player0} crush01 ${player1}`, 1],
      [`${player0} crush02 ${player1}`, 2],
      [`${player0} crush03 ${player1}`, 3],
      [`${player0} crush04 ${player1}`, 4],
      [`${player0} crush05 ${player1}`, 5],
      [`${player0} crush06 ${player1}`, 6],
      [`${player0} crush07 ${player1}`, 7],
      [`${player0} crush08 ${player1}`, 8],
      [`${player0} crush09 ${player1}`, 9],
      [`${player0} crush10 ${player1}`, 10],
    ],
    differentSex: [
      [`${player0} differentSex01 ${player1}`, 1],
      [`${player0} differentSex02 ${player1}`, 2],
      [`${player0} differentSex03 ${player1}`, 3],
      [`${player0} differentSex04 ${player1}`, 4],
      [`${player0} differentSex05 ${player1}`, 5],
      [`${player0} differentSex06 ${player1}`, 6],
      [`${player0} differentSex07 ${player1}`, 7],
      [`${player0} differentSex08 ${player1}`, 8],
      [`${player0} differentSex09 ${player1}`, 9],
      [`${player0} differentSex10 ${player1}`, 10],
    ],
    sameSex: [
      [`${player0} sameSex01 ${player1}`, 1],
      [`${player0} sameSex02 ${player1}`, 2],
      [`${player0} sameSex03 ${player1}`, 3],
      [`${player0} sameSex04 ${player1}`, 4],
      [`${player0} sameSex05 ${player1}`, 5],
      [`${player0} sameSex06 ${player1}`, 6],
      [`${player0} sameSex07 ${player1}`, 7],
      [`${player0} sameSex08 ${player1}`, 8],
      [`${player0} sameSex09 ${player1}`, 9],
      [`${player0} sameSex10 ${player1}`, 10],
    ],
    imaginaryTask: `${player1} denke dir eine Aufgabe für ${player0} aus!`,
    probabilityNormal: 0.45,
    probabilityPartnerCrush: 0.45,
  }
}
